### ISSUE TITLE
PHP ERROR, SERVER CONNECT

### ISSUE THREAD

**Issue by JuanseMastrangelo** [amirsanni/Video-Call-App#35]
**Hi, i have this error on Ratchet server. Please help! :(**

```

PHP Fatal error:  Uncaught Error: Class 'GuzzleHttp\Psr7\Rfc7230' not found in C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php:792
Stack trace:
#0 C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php(469): GuzzleHttp\Psr7\_parse_message('GET /ws/comm HT...')
#1 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpRequestParser.php(73): GuzzleHttp\Psr7\parse_request('GET /ws/comm HT...')
#2 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpRequestParser.php(40): Ratchet\Http\HttpRequestParser->parse('GET /ws/comm HT...')
#3 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpServer.php(42): Ratchet\Http\HttpRequestParser->onMessage(Object(Ratchet\Server\IoConnection), 'GET /ws/comm HT...')
#4 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Server\IoServer.php(113): Ratchet\Http\HttpServer->onMessage(Object(Ratchet\Server\IoConnection), 'GET /ws/comm HT...')
#5 C:\xampp\htdocs\video-cal in C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php on line 792

Fatal error: Uncaught Error: Class 'GuzzleHttp\Psr7\Rfc7230' not found in C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php:792
Stack trace:
#0 C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php(469): GuzzleHttp\Psr7\_parse_message('GET /ws/comm HT...')
#1 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpRequestParser.php(73): GuzzleHttp\Psr7\parse_request('GET /ws/comm HT...')
#2 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpRequestParser.php(40): Ratchet\Http\HttpRequestParser->parse('GET /ws/comm HT...')
#3 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Http\HttpServer.php(42): Ratchet\Http\HttpRequestParser->onMessage(Object(Ratchet\Server\IoConnection), 'GET /ws/comm HT...')
#4 C:\xampp\htdocs\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Server\IoServer.php(113): Ratchet\Http\HttpServer->onMessage(Object(Ratchet\Server\IoConnection), 'GET /ws/comm HT...')
#5 C:\xampp\htdocs\video-cal in C:\xampp\htdocs\video-call-app\ws\vendor\guzzlehttp\psr7\src\functions.php on line 792
```

**Comment by amirsanni** [comment]
Try `composer dump-autoload` to see if it will fix the issue. Also, do `composer update`.

**Comment by GurjantKamboj** [comment]
which folder this command will be run ?

**Comment by rozel07** [comment]
hi, when i execute this line php ws/bin/server.php to my CLi nothings happen.
And also i got this error No webpage was found for the web address: http://localhost:8888/

Thank you.
